extends Node

# This script no longer calculates damage. 
# It only helps visualizing the result sent by the Server.

func request_battle_start(target_node):
	# Instead of simulating locally, we tell the Network to ask the server
	var target_id = target_node.get_meta("guild_id") # or enemy_name
	NetworkManager.send_action("attack", target_id)

func play_battle_replay(server_log):
	print("--- RECEIVING BATTLE DATA FROM SERVER ---")
	# This function takes the log generated by Go and formats it for the UI
	
	# You can pass this log directly to your existing BattleResult UI
	# located in Main.gd or battle_result.gd
	var formatted_log = []
	for round_data in server_log:
		formatted_log.append(round_data)
		
	# Find the Main scene and show result
	var main_node = get_tree().get_root().get_node("Main")
	if main_node:
		# You need to determine victory/casualties from the server packet
		var is_victory = server_log.victory
		main_node.battle_result_ui.show_result(is_victory, 0, formatted_log, {}, {})
